version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: workout
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: .
    depends_on:
      - db
    ports:
      - "4001:4001"
    environment:
      PORT: "4001"
      DATABASE_URL: "root:nusa123@tcp(db:3306)/workout?parseTime=true"
volumes:
  db_data: